name: Deploy Site from Master
on:
  # Manual trigger for testing
  workflow_dispatch:
  
  # Repository dispatch (for n8n to trigger)
  repository_dispatch:
    types: [deploy-trigger]

jobs:
  deploy:
    uses: monolithseo/pgp_floodcleanuppros_master/.github/workflows/site-deploy-template.yml@main
    with:
      source_folder: cities/water-damage-restoration-aventura-fl  # Change this for each site!
      target_repo: ${{ github.repository }}
    secrets:
      MASTER_REPO_TOKEN: ${{ secrets.MASTER_REPO_TOKEN }}
